package io.github.sunthemoon.advancedrocketrycommunity.satellite.mission;

import io.github.sunthemoon.advancedrocketrycommunity.satellite.model.SatelliteKind;
import io.github.sunthemoon.advancedrocketrycommunity.satellite.model.SatelliteLimits;
import io.github.sunthemoon.advancedrocketrycommunity.satellite.model.SatelliteState;
import io.github.sunthemoon.advancedrocketrycommunity.satellite.model.SatelliteStatus;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.OptionalLong;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import net.minecraft.resources.ResourceLocation;

/**
 * ADR-051 survey, asteroid and gas missions on the registry: starts, claims, cancels, delivery reconciliation,
 * rebind, purge and instance release. Every operation holds the registry's lock and changes the mission, its
 * instances and its satellite in one mutation (ADR-051 section 2). Rewards and instances are generated by the
 * caller (ADR-052); this class only admits, moves and checks records.
 */
public final class ResourceMissions {
    public static final String SURVEY_REWARD_VERSION = "survey-v1";

    private final SatelliteMissionRegistry registry;
    /** Acknowledged claims whose acknowledgement is not durable yet (ack_epoch ≥ E); derived, never persisted. */
    private final Set<UUID> acknowledging = new HashSet<>();

    ResourceMissions(SatelliteMissionRegistry registry) {
        this.registry = Objects.requireNonNull(registry, "registry");
    }

    /** Creates the {@code count} PENDING instances of one survey at {@code createdAt} (ADR-052 survey-v1). */
    @FunctionalInterface
    public interface SurveyGeneration {
        List<AsteroidInstance> generate(int count, long createdAt);
    }

    public record SurveyStart(UUID satelliteId, UUID missionId, UUID ownerId, ResourceLocation system,
                              String candidateFingerprint, int requestedInstances, int durationTicks, long seed,
                              SurveyGeneration generation) {
        public SurveyStart {
            Objects.requireNonNull(generation, "generation");
            if (requestedInstances < 1 || requestedInstances > SatelliteLimits.MAX_INSTANCES_PER_SURVEY
                    || durationTicks < 1) {
                throw new IllegalArgumentException("Survey start is outside its bounds");
            }
        }
    }

    /** An asteroid (with its instance) or gas start; the reward and duration were computed at start (ADR-052). */
    public record ResourceStart(UUID satelliteId, UUID missionId, UUID ownerId, MissionKind kind,
                                ResourceLocation targetBody, Optional<UUID> instanceId, List<RewardEntry> reward,
                                String rewardVersion, int durationTicks, long seed, UUID terminal,
                                Optional<MissionPayload.TerminalLocation> display) {
        public ResourceStart {
            Objects.requireNonNull(kind, "kind");
            if (!kind.resource() || (kind == MissionKind.ASTEROID) != instanceId.isPresent() || durationTicks < 1) {
                throw new IllegalArgumentException("Resource start is inconsistent");
            }
        }
    }

    /** What reconciliation found and did for one mission at one terminal (ADR-051 section 7). */
    public record Reconciled(DeliveryReconciliation.Action action, Optional<MissionState> mission, boolean changed,
                             boolean barrier) {
        public static Reconciled blocked() {
            return new Reconciled(DeliveryReconciliation.Action.NONE_REGISTRY_BLOCKED, Optional.empty(), false, false);
        }
    }

    public SatelliteOperationResult startSurvey(SurveyStart start, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            SatelliteState satellite = registry.satelliteRecord(start.satelliteId());
            SatelliteOperationResult refused = idleCraft(satellite, start.ownerId(), SatelliteKind.SURVEY,
                    start.missionId());
            if (refused != null) {
                return refused;
            }
            int remaining = registry.limits().instancesPerOwner() - registry.ledger().live(start.ownerId());
            if (remaining <= 0) {
                return registry.result(SatelliteOperationCode.OWNER_LIMIT, false, satellite, null);
            }
            int count = Math.min(start.requestedInstances(), remaining);
            if (registry.instanceCount() + count > Math.min(registry.limits().instancesGlobal(),
                    SatelliteLimits.MAX_INSTANCES)) {
                return registry.result(SatelliteOperationCode.CAPACITY_REACHED, false, satellite, null);
            }
            List<AsteroidInstance> created = List.copyOf(start.generation().generate(count, now));
            List<UUID> ids = created.stream().map(AsteroidInstance::instanceId).toList();
            if (created.size() != count || new HashSet<>(ids).size() != count || created.stream().anyMatch(instance ->
                    instance.state() != InstanceState.PENDING || !instance.ownerId().equals(start.ownerId())
                            || !instance.sourceMission().equals(start.missionId())
                            || !instance.system().equals(start.system())
                            || registry.instanceRecord(instance.instanceId()) != null)) {
                throw new IllegalArgumentException("Survey generation returned inconsistent instances");
            }
            MissionState mission;
            try {
                mission = new MissionState(SatelliteLimits.MISSION_SCHEMA_VERSION, start.missionId(),
                        start.satelliteId(), start.ownerId(), satellite.definitionId(), MissionKind.SURVEY,
                        start.system(), Optional.empty(), start.seed(), now, Math.addExact(now, start.durationTicks()),
                        registry.saveEpoch(), MissionStatus.ACTIVE, OptionalLong.empty(), OptionalLong.empty(),
                        SURVEY_REWARD_VERSION, Optional.empty(),
                        new MissionPayload.Survey(ids, start.candidateFingerprint()));
            } catch (ArithmeticException exception) {
                return registry.result(SatelliteOperationCode.CAPACITY_REACHED, false, satellite, null);
            }
            SatelliteOperationCode admission = registry.admission(start.ownerId(), null, mission);
            if (admission == null && !registry.instancesFit(created)) {
                admission = SatelliteOperationCode.STORAGE_BUDGET;
            }
            if (admission != null) {
                return registry.result(admission, false, satellite, null);
            }
            registry.admit(mission, created);
            SatelliteState updated = satellite.startMission(mission.missionId());
            registry.storeSatellite(updated);
            return registry.result(SatelliteOperationCode.SUCCESS, true, updated, mission);
        }
    }

    public SatelliteOperationResult startResource(ResourceStart start, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            SatelliteState satellite = registry.satelliteRecord(start.satelliteId());
            SatelliteKind craft = start.kind() == MissionKind.ASTEROID
                    ? SatelliteKind.ASTEROID_MINER : SatelliteKind.GAS_HARVESTER;
            SatelliteOperationResult refused = idleCraft(satellite, start.ownerId(), craft, start.missionId());
            if (refused != null) {
                return refused;
            }
            AsteroidInstance instance = start.instanceId().map(registry::instanceRecord).orElse(null);
            if (start.instanceId().isPresent()) {
                SatelliteOperationCode unusable = instance == null ? SatelliteOperationCode.INSTANCE_NOT_FOUND
                        : !instance.ownerId().equals(start.ownerId()) ? SatelliteOperationCode.UNAUTHORIZED
                        : instance.state() != InstanceState.AVAILABLE || !instance.system().equals(start.targetBody())
                                || instance.expiresAt().getAsLong() <= now
                        ? SatelliteOperationCode.TARGET_NOT_ALLOWED : null;
                if (unusable != null) {
                    return registry.result(unusable, false, satellite, null);
                }
            }
            MissionState mission;
            try {
                mission = new MissionState(SatelliteLimits.MISSION_SCHEMA_VERSION, start.missionId(),
                        start.satelliteId(), start.ownerId(), satellite.definitionId(), start.kind(),
                        start.targetBody(), start.instanceId(), start.seed(), now,
                        Math.addExact(now, start.durationTicks()), registry.saveEpoch(), MissionStatus.ACTIVE,
                        OptionalLong.empty(), OptionalLong.empty(), start.rewardVersion(), Optional.empty(),
                        new MissionPayload.Resource(start.kind(), start.reward(), start.terminal(), start.display(),
                                false, Optional.empty(), false, OptionalLong.empty()));
            } catch (ArithmeticException exception) {
                return registry.result(SatelliteOperationCode.CAPACITY_REACHED, false, satellite, null);
            }
            SatelliteOperationCode admission = registry.admission(start.ownerId(), null, mission);
            if (admission != null) {
                return registry.result(admission, false, satellite, null);
            }
            registry.admit(mission, List.of());
            if (instance != null) {
                registry.storeInstance(instance.transition(InstanceState.ALLOCATED, instance.expiresAt(),
                        Optional.of(mission.missionId())));
            }
            SatelliteState updated = satellite.startMission(mission.missionId());
            registry.storeSatellite(updated);
            return registry.result(SatelliteOperationCode.SUCCESS, true, updated, mission);
        }
    }

    /** A survey claim at any terminal: instances PENDING → AVAILABLE for {@code ttlTicks} (ADR-051 section 3). */
    public SatelliteOperationResult claimSurvey(UUID missionId, UUID ownerId, long ttlTicks, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            SatelliteOperationResult refused = claimable(registry.missionRecord(missionId), ownerId, true, now);
            if (refused != null) {
                return refused;
            }
            MissionState mission = registry.missionRecord(missionId);
            MissionState claimed = mission.beginClaim(now);
            long expiresAt = Math.addExact(now, ttlTicks);
            for (UUID id : ((MissionPayload.Survey) mission.payload()).instances()) {
                AsteroidInstance instance = registry.instanceRecord(id);
                if (instance != null && instance.state() == InstanceState.PENDING
                        && instance.sourceMission().equals(missionId)) {
                    registry.storeInstance(instance.transition(InstanceState.AVAILABLE, OptionalLong.of(expiresAt),
                            Optional.empty()));
                }
            }
            registry.putMission(claimed);
            return registry.result(SatelliteOperationCode.SUCCESS, true, registry.release(mission), claimed);
        }
    }

    /**
     * An asteroid or gas claim at the bound terminal (ADR-051 section 6). {@code delivery} names the terminal's
     * refusal for this reward (buffer or receipts full), or null when the terminal can take it whole.
     */
    public SatelliteOperationResult claimResource(UUID missionId, UUID ownerId, UUID terminal,
                                                  Function<List<RewardEntry>, SatelliteOperationCode> delivery,
                                                  long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            MissionState before = registry.missionRecord(missionId);
            SatelliteOperationResult refused = claimable(before, ownerId, false, now);
            if (refused != null) {
                return refused;
            }
            MissionState mission = registry.missionRecord(missionId);
            // A lazy completion is a change even when the claim is then refused (ADR-050 section 2).
            boolean completed = mission != before;
            MissionPayload.Resource resource = (MissionPayload.Resource) mission.payload();
            SatelliteState satellite = registry.satelliteRecord(mission.satelliteId());
            SatelliteOperationCode code = !resource.boundTerminal().equals(terminal)
                    ? SatelliteOperationCode.WRONG_TERMINAL : delivery.apply(resource.reward());
            if (code == null && mission.startEpoch() >= registry.saveEpoch()) {
                code = SatelliteOperationCode.AWAITING_WORLD_SAVE;
            }
            if (code != null) {
                return registry.result(code, completed, satellite, mission);
            }
            MissionState claimed = settle(mission, resource.paidAt(terminal), now);
            return registry.result(SatelliteOperationCode.SUCCESS, true, registry.satelliteRecord(
                    mission.satelliteId()), claimed);
        }
    }

    /**
     * ADR-050 section 8 and ADR-051 section 8. An owner cancels an asteroid or gas mission only at its bound
     * terminal ({@code atTerminal}); an operator cancel, the cancel of a QUARANTINED mission and the cancel of a
     * rebound mission put its instance in QUARANTINED. A survey cancel deletes its PENDING instances.
     */
    public SatelliteOperationResult cancel(UUID missionId, UUID requesterId, boolean operator,
                                           Optional<UUID> atTerminal, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            MissionState mission = registry.missionRecord(missionId);
            if (mission == null) {
                return registry.result(SatelliteOperationCode.MISSION_NOT_FOUND, false, null, null);
            }
            SatelliteState satellite = registry.satelliteRecord(mission.satelliteId());
            SatelliteOperationCode code = !operator && !mission.ownerId().equals(requesterId)
                    ? SatelliteOperationCode.UNAUTHORIZED
                    : mission.status() == MissionStatus.CANCELLED ? SatelliteOperationCode.CANCELLED
                    : !mission.status().unfinished() || mission.phase() == MissionStatus.CLAIM_PENDING_DISCOVERY
                    ? SatelliteOperationCode.ALREADY_CLAIMED
                    : mission.status() == MissionStatus.QUARANTINED && !operator
                    ? SatelliteOperationCode.RECOVERY_REQUIRED
                    : mission.payload() instanceof MissionPayload.Resource resource && !operator
                            && !atTerminal.filter(resource.boundTerminal()::equals).isPresent()
                    ? SatelliteOperationCode.WRONG_TERMINAL : null;
            if (code != null) {
                return registry.result(code, false, satellite, mission);
            }
            boolean held = operator || mission.status() == MissionStatus.QUARANTINED
                    || mission.payload() instanceof MissionPayload.Resource resource && resource.rebound();
            MissionState cancelled = mission.cancel(now);
            registry.putMission(cancelled);
            registry.unschedule(missionId);
            if (mission.payload() instanceof MissionPayload.Survey survey) {
                for (UUID id : survey.instances()) {
                    AsteroidInstance instance = registry.instanceRecord(id);
                    if (instance != null && instance.state() == InstanceState.PENDING
                            && instance.sourceMission().equals(missionId)) {
                        registry.dropInstance(id);
                    }
                }
            }
            AsteroidInstance instance = allocated(mission);
            if (instance != null) {
                long expiresAt = instance.expiresAt().orElseThrow();
                registry.storeInstance(held ? instance.quarantine() : instance.transition(
                        expiresAt > now ? InstanceState.AVAILABLE : InstanceState.EXPIRED, instance.expiresAt(),
                        Optional.empty()));
            }
            return registry.result(SatelliteOperationCode.SUCCESS, true, registry.release(mission), cancelled);
        }
    }

    /** One row of the ADR-051 section 7 table for {@code missionId} at {@code terminal}. */
    public Reconciled reconcile(UUID terminal, UUID missionId, DeliveryReconciliation.ReceiptView receipt,
                                Optional<MissionPayload.TerminalLocation> display, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            MissionState mission = registry.missionRecord(missionId);
            long epoch = registry.saveEpoch();
            DeliveryReconciliation.Action action = DeliveryReconciliation.decide(
                    DeliveryReconciliation.view(true, Optional.ofNullable(mission), terminal, epoch), receipt);
            MissionState next = switch (action) {
                case SET_CLAIMED_PAID_HERE -> settle(mission, resource(mission).paidAt(terminal), now);
                case SET_CLAIMED_PAID_HERE_BIND_BACK -> settle(mission,
                        resource(mission).boundTo(terminal, display, resource(mission).rebound()).paidAt(terminal), now);
                case ACKNOWLEDGE -> {
                    MissionState acknowledged = mission.withPayload(resource(mission).acknowledgedAt(epoch));
                    registry.putMission(acknowledged);
                    acknowledging.add(missionId);
                    yield acknowledged;
                }
                case KEEP_MARK_RECEIPT_SEEN -> {
                    if (mission.quarantine().orElseThrow().receiptSeen()) {
                        yield null;
                    }
                    MissionState seen = mission.markReceiptSeen();
                    registry.putMission(seen);
                    yield seen;
                }
                default -> null;
            };
            return new Reconciled(action, Optional.ofNullable(next != null ? next : mission), next != null,
                    action == DeliveryReconciliation.Action.SET_CLAIMED_PAID_HERE_BIND_BACK);
        }
    }

    /** ADR-051 section 9: an operator binds a READY mission to another terminal whose ID is persisted. */
    public SatelliteOperationResult rebind(UUID missionId, UUID terminal,
                                           Optional<MissionPayload.TerminalLocation> display, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            MissionState mission = registry.missionRecord(missionId);
            if (mission == null || !mission.kind().resource()) {
                return registry.result(mission == null ? SatelliteOperationCode.MISSION_NOT_FOUND
                        : SatelliteOperationCode.DEFINITION_NOT_FOUND, false, null, mission);
            }
            MissionState before = mission;
            mission = completeIfDue(mission, now);
            SatelliteState satellite = registry.satelliteRecord(mission.satelliteId());
            if (mission.status() != MissionStatus.READY) {
                return registry.result(mission.status() == MissionStatus.ACTIVE ? SatelliteOperationCode.NOT_READY
                        : mission.status() == MissionStatus.QUARANTINED ? SatelliteOperationCode.RECOVERY_REQUIRED
                        : SatelliteOperationCode.ALREADY_CLAIMED, false, satellite, mission);
            }
            MissionPayload.Resource resource = resource(mission);
            if (resource.boundTerminal().equals(terminal)) {
                return registry.result(SatelliteOperationCode.IDEMPOTENT, mission != before, satellite, mission);
            }
            MissionState rebound = mission.withPayload(resource.boundTo(terminal, display, true));
            registry.putMission(rebound);
            return registry.result(SatelliteOperationCode.SUCCESS, true, satellite, rebound);
        }
    }

    /** ADR-050 section 7: an operator removes a CLAIMED resource record that no terminal acknowledged. */
    public SatelliteOperationResult purge(UUID missionId) {
        synchronized (registry) {
            MissionState mission = registry.missionRecord(missionId);
            if (mission == null || !mission.kind().resource()) {
                return registry.result(mission == null ? SatelliteOperationCode.MISSION_NOT_FOUND
                        : SatelliteOperationCode.DEFINITION_NOT_FOUND, false, null, mission);
            }
            if (mission.status() != MissionStatus.CLAIMED || resource(mission).acknowledged()) {
                return registry.result(mission.status() == MissionStatus.CLAIMED ? SatelliteOperationCode.IDEMPOTENT
                        : SatelliteOperationCode.MISSION_BUSY, false, null, mission);
            }
            registry.removeMission(mission);
            acknowledging.remove(missionId);
            return registry.result(SatelliteOperationCode.SUCCESS, true, null, mission);
        }
    }

    /**
     * ADR-051 section 2: an operator returns a QUARANTINED instance to AVAILABLE, or EXPIRED once its expiry has
     * passed. An instance still allocated to an unfinished or claimed mission is refused.
     */
    public SatelliteOperationResult releaseInstance(UUID instanceId, long ttlTicks, long observedGameTime) {
        synchronized (registry) {
            long now = registry.advanceClock(observedGameTime);
            AsteroidInstance instance = registry.instanceRecord(instanceId);
            if (instance == null) {
                return registry.result(SatelliteOperationCode.INSTANCE_NOT_FOUND, false, null, null);
            }
            if (instance.state() != InstanceState.QUARANTINED) {
                return registry.result(SatelliteOperationCode.IDEMPOTENT, false, null, null);
            }
            MissionState mission = instance.allocatedMission().map(registry::missionRecord).orElse(null);
            if (mission != null && (mission.status().unfinished() || mission.status() == MissionStatus.CLAIMED)) {
                return registry.result(mission.status() == MissionStatus.CLAIMED
                        ? SatelliteOperationCode.ALREADY_CLAIMED : SatelliteOperationCode.MISSION_BUSY,
                        false, null, mission);
            }
            OptionalLong expiresAt = instance.expiresAt().isPresent() ? instance.expiresAt()
                    : OptionalLong.of(Math.addExact(now, ttlTicks));
            registry.storeInstance(instance.transition(expiresAt.getAsLong() > now ? InstanceState.AVAILABLE
                    : InstanceState.EXPIRED, expiresAt, Optional.empty()));
            return registry.result(SatelliteOperationCode.SUCCESS, true, null, mission);
        }
    }

    /** The owner's AVAILABLE, unexpired instances of one system, in ID order. */
    public List<AsteroidInstance> available(UUID ownerId, ResourceLocation system) {
        synchronized (registry) {
            long now = registry.logicalGameTime();
            List<AsteroidInstance> values = new ArrayList<>();
            for (UUID id : registry.ledger().owned(ownerId)) {
                AsteroidInstance instance = registry.instanceRecord(id);
                if (instance != null && instance.state() == InstanceState.AVAILABLE
                        && instance.system().equals(system) && instance.expiresAt().getAsLong() > now) {
                    values.add(instance);
                }
            }
            return List.copyOf(values);
        }
    }

    /** Every instance record of one owner, in ID order. */
    public List<AsteroidInstance> owned(UUID ownerId) {
        synchronized (registry) {
            return registry.ledger().owned(ownerId).stream().map(registry::instanceRecord).toList();
        }
    }

    /** Resource missions bound to one terminal, in ID order (ADR-051 section 7 index). */
    public List<MissionState> boundTo(UUID terminal) {
        synchronized (registry) {
            return registry.boundTo(terminal).stream().map(registry::missionRecord).toList();
        }
    }

    public int liveInstances(UUID ownerId) {
        synchronized (registry) {
            return registry.ledger().live(ownerId);
        }
    }

    /** Called after the save epoch advanced: acknowledgements that are now durable become prunable. */
    void epochAdvanced() {
        long epoch = registry.saveEpoch();
        List<MissionState> durable = new ArrayList<>();
        for (Iterator<UUID> iterator = acknowledging.iterator(); iterator.hasNext(); ) {
            MissionState mission = registry.missionRecord(iterator.next());
            if (mission == null || !(mission.payload() instanceof MissionPayload.Resource resource)
                    || !resource.acknowledged()) {
                iterator.remove();
            } else if (resource.ackEpoch().orElseThrow() < epoch) {
                durable.add(mission);
                iterator.remove();
            }
        }
        registry.reoffer(durable);
    }

    /** Restore hook: an acknowledgement read from a file is normally durable already. */
    void restored(MissionState mission) {
        if (mission.payload() instanceof MissionPayload.Resource resource && resource.acknowledged()
                && resource.ackEpoch().orElseThrow() >= registry.saveEpoch()) {
            acknowledging.add(mission.missionId());
        }
    }

    /** Sets CLAIMED with this payload and applies the claim's side effects (ADR-050 section 4). */
    private MissionState settle(MissionState mission, MissionPayload.Resource paid, long now) {
        MissionState claimed = mission.claimWith(now, paid);
        registry.putMission(claimed);
        registry.unschedule(mission.missionId());
        AsteroidInstance instance = allocated(mission);
        if (instance != null) {
            registry.storeInstance(instance.transition(InstanceState.DEPLETED,
                    OptionalLong.of(Math.max(instance.createdAt(), now)), instance.allocatedMission()));
        }
        registry.release(mission);
        return claimed;
    }

    /**
     * Refusals shared by claims; completes a due ACTIVE mission first (the lazy completion of ADR-050). A completed
     * mission is READY, which is never refused here.
     */
    private SatelliteOperationResult claimable(MissionState mission, UUID ownerId, boolean survey, long now) {
        if (mission == null) {
            return registry.result(SatelliteOperationCode.MISSION_NOT_FOUND, false, null, null);
        }
        SatelliteState satellite = registry.satelliteRecord(mission.satelliteId());
        boolean kindMatches = survey ? mission.kind() == MissionKind.SURVEY : mission.kind().resource();
        if (!kindMatches || !mission.ownerId().equals(ownerId)) {
            return registry.result(kindMatches ? SatelliteOperationCode.UNAUTHORIZED
                    : SatelliteOperationCode.DEFINITION_NOT_FOUND, false, satellite, mission);
        }
        mission = completeIfDue(mission, now);
        SatelliteOperationCode code = switch (mission.status()) {
            case QUARANTINED -> SatelliteOperationCode.RECOVERY_REQUIRED;
            case ACTIVE -> SatelliteOperationCode.NOT_READY;
            case CANCELLED -> SatelliteOperationCode.CANCELLED;
            case CLAIMED, CLAIM_PENDING_DISCOVERY -> SatelliteOperationCode.ALREADY_CLAIMED;
            case READY -> null;
        };
        return code == null ? null : registry.result(code, false, satellite, mission);
    }

    private MissionState completeIfDue(MissionState mission, long now) {
        if (mission.status() != MissionStatus.ACTIVE || now < mission.completesAtLogicalTime()) {
            return mission;
        }
        MissionState ready = mission.complete(now);
        registry.putMission(ready);
        registry.unschedule(mission.missionId());
        return ready;
    }

    /** The instance this asteroid mission holds ALLOCATED, or null. */
    private AsteroidInstance allocated(MissionState mission) {
        AsteroidInstance instance = mission.instanceId().map(registry::instanceRecord).orElse(null);
        return instance != null && instance.state() == InstanceState.ALLOCATED
                && instance.allocatedMission().filter(mission.missionId()::equals).isPresent() ? instance : null;
    }

    /** An operational, idle craft of the right kind owned by the requester, or the refusal. */
    private SatelliteOperationResult idleCraft(SatelliteState satellite, UUID ownerId, SatelliteKind kind,
                                               UUID missionId) {
        if (satellite == null) {
            return registry.result(SatelliteOperationCode.SATELLITE_NOT_FOUND, false, null, null);
        }
        MissionState current = satellite.currentMissionId().map(registry::missionRecord).orElse(null);
        SatelliteOperationCode code = !satellite.ownerId().equals(ownerId) ? SatelliteOperationCode.UNAUTHORIZED
                : satellite.status() != SatelliteStatus.OPERATIONAL ? SatelliteOperationCode.RECOVERY_REQUIRED
                : satellite.kind() != kind ? SatelliteOperationCode.DEFINITION_NOT_FOUND
                : current != null && current.missionId().equals(missionId) ? SatelliteOperationCode.IDEMPOTENT
                : satellite.currentMissionId().isPresent() ? SatelliteOperationCode.MISSION_BUSY
                : registry.missionRecord(missionId) != null ? SatelliteOperationCode.IDENTITY_CONFLICT : null;
        return code == null ? null : registry.result(code, false, satellite,
                code == SatelliteOperationCode.IDENTITY_CONFLICT ? registry.missionRecord(missionId) : current);
    }

    private static MissionPayload.Resource resource(MissionState mission) {
        return (MissionPayload.Resource) mission.payload();
    }
}
